# Generated by Django 4.2 on 2023-04-14 17:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_remove_oauth2client_user_alter_user_tenant"),
    ]

    operations = [
        migrations.AddField(
            model_name="authorizationcode",
            name="code_challenge",
            field=models.TextField(default="", null=True),
        ),
        migrations.AddField(
            model_name="authorizationcode",
            name="code_challenge_method",
            field=models.TextField(default="", null=True),
        ),
    ]
