# Generated by Django 4.2 on 2023-04-14 19:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_authorizationcode_code_challenge_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="oauth2client",
            name="default_redirect_uri",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="oauth2client",
            name="redirect_uris",
            field=models.TextField(blank=True, default=""),
        ),
    ]
