# Generated by Django 4.2 on 2023-04-15 07:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_oauth2client_default_redirect_uri_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="oauth2token",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
