# Generated by Django 4.2 on 2023-04-15 07:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_alter_oauth2token_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="oauth2client",
            name="require_nonce",
            field=models.BooleanField(default=False),
        ),
    ]
