# Generated by Django 4.2 on 2023-04-15 15:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_oauth2client_require_code_challenge"),
    ]

    operations = [
        migrations.AlterField(
            model_name="oauth2client",
            name="grant_type",
            field=models.TextField(
                choices=[
                    ("authorization_code", "authorization_code"),
                    ("client_credentials", "client_credentials"),
                    ("device_code", "urn:ietf:params:oauth:grant-type:device_code"),
                    ("implicit", "implicit"),
                    ("password", "password"),
                    ("refresh_token", "refresh_token"),
                ],
                default="",
                help_text='\nOAuth2/OpenID Connect grant types. Recommended grant types are:<br>\n<ul>\n<li><a href="https://oauth.net/2/grant-types/authorization-code/">authorization_code</a> (optionally with <a href="https://oauth.net/2/pkce/">PKCE</a>)</li>\n<li><a href="https://oauth.net/2/grant-types/refresh-token/">refresh_token</a></li>\n<li><a href="https://oauth.net/2/grant-types/device-code/">device code</a></li>\n<li><a href="https://oauth.net/2/grant-types/client-credentials/">client_credentials</a> (for server-to-server communication)</li>\n</ul>\n\nLegacy, not recommended\n<ul>\n<li><a href="https://oauth.net/2/grant-types/implicit/">implicit</a> (not recommended, using access_token in URL)</li>\n<li>password (not recommended, using username and password)</li>\n</ul>\n\n',
            ),
        ),
    ]
