# Generated by Django 4.2 on 2023-04-29 11:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_alter_user_managers_user_email_verified_and_more"),
    ]

    database_operations = [
        migrations.AlterModelTable("AuthorizationCode", "oauth"),
        migrations.AlterModelTable("OAuth2Client", "oauth"),
        migrations.AlterModelTable("OAuth2Token", "oauth"),
    ]

    state_operations = [
        migrations.DeleteModel("AuthorizationCode"),
        migrations.DeleteModel("OAuth2Client"),
        migrations.DeleteModel("OAuth2Token"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations,
        ),
    ]
