# Generated by Django 4.2 on 2023-05-20 22:23
import uuid

from django.apps.registry import Apps
from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor


def gen_uuid(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    tenant_model_class = apps.get_model("core", "Tenant")
    for row in tenant_model_class.objects.all():
        row.uid = uuid.uuid4()
        row.save(update_fields=["uid"])


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_tenant_uid"),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
