# Generated by Django 4.2 on 2023-05-20 22:28
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0018_alter_tenant_id"),
    ]

    operations = [
        migrations.RunSQL(
            """
UPDATE core_user SET tenant_id = core_tenant.uid FROM core_tenant WHERE core_tenant.id = core_user.tenant_id;
UPDATE oauth_oauth2client SET tenant_id = core_tenant.uid FROM core_tenant WHERE core_tenant.id = oauth_oauth2client.tenant_id;
UPDATE oauth_oauth2authorizedapp SET tenant_id = core_tenant.uid FROM core_tenant WHERE core_tenant.id = oauth_oauth2authorizedapp.tenant_id;
UPDATE core_tenant SET id = uid;
""",
        ),
    ]
