# Generated by Django 4.2 on 2023-05-20 22:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0019_auto_20230520_2228"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tenant",
            name="uid",
        ),
    ]
