# Generated by Django 4.2 on 2023-05-26 21:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0021_tenant_certificate_pem"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="display_name",
            field=models.TextField(default="Name"),
            preserve_default=False,
        ),
    ]
