# Generated by Django 4.2 on 2023-05-29 11:13

from django.apps.registry import Apps
from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor


def update_grants(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    client_model_class = apps.get_model("oauth", "OAuth2Client")
    for client in client_model_class.objects.all():
        if client.grant_type == "client_credentials":
            client.client_credentials_grant = True
        elif client.grant_type == "authorization_code":
            client.authorization_code_grant = True
        elif client.grant_type == "password":
            client.password_grant = True
        elif client.grant_type == "device_code":
            client.device_code_grant = True
        elif client.grant_type == "refresh_token":
            client.refresh_token_grant = True
        elif client.grant_type == "implicit":
            client.implicit_grant = True
        client.save(
            update_fields=[
                "client_credentials_grant",
                "authorization_code_grant",
                "password_grant",
                "device_code_grant",
                "implicit_grant",
                "refresh_token_grant",
            ],
        )


class Migration(migrations.Migration):
    dependencies = [
        ("oauth", "0004_oauth2client_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="oauth2client",
            name="authorization_code_grant",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="oauth2client",
            name="client_credentials_grant",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="oauth2client",
            name="device_code_grant",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="oauth2client",
            name="implicit_grant",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="oauth2client",
            name="password_grant",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="oauth2client",
            name="refresh_token_grant",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="oauth2client",
            name="token_endpoint_auth_method",
            field=models.CharField(
                choices=[
                    ("client_secret_basic", "client_secret_basic"),
                    ("client_secret_post", "client_secret_post"),
                    ("client_secret_jwt", "client_secret_jwt"),
                    ("private_key_jwt", "private_key_jwt"),
                    ("none", "none"),
                ],
                default="",
                help_text='\n* client_secret_basic uses the HTTP Basic Authentication Scheme\nto authenticate.<br>\n<br>\n* client_secret_post uses the HTTP POST parameters to authenticate.<br>\n<br>\n* client_secret_jwt uses the JSON Web Token (JWT) to authenticate.\nCompared to client_secret_basic and client_secret_post, client_secret_jwt\ndoesn`t require sending the actual secret over the network.\nThis makes it more secure.<br>\n<br>\n* <a href="https://oauth.net/private-key-jwt/">private_key_jwt</a> uses\nthe JSON Web Token (JWT) to authenticate. Compared to client_secret_jwt,\nprivate_key_jwt uses a private key to sign the JWT. This makes it more secure.<br>\n',
                max_length=120,
            ),
        ),
        migrations.RunPython(update_grants, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="oauth2client",
            name="grant_type",
        ),
    ]
